### ISSUE TITLE
Code typo in dplfit.R (ln 51-52)

### ISSUE THREAD

**Issue by marghetis** [mnewberry/dplfit#1]
On line 51 on dlpfit.R, a new function is defined but the function code is on a new line (ln 52) and not surrounded by {}. Either add {} or move the function code on line 52 to line 51.

**Comment by mnewberry** [comment]
Hi, thanks for your report. It's fine to add {}, but I'm curious: do lines 51-52 work for you? or what version of R are you running that they do not work? It works on my version of R (3.5.1).

**Comment by mnewberry** [comment]
fixed in any case in e8e70fd
